// <auto-generated />
using System;
using Backend.Sprints.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Sprints.Api.Migrations
{
    [DbContext(typeof(SprintsDbContext))]
    [Migration("20251118154756_StatusAdd")]
    partial class StatusAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sprints_service_schema")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Sprints.Api.Models.Entities.Sprint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Planned")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("sprints", "sprints_service_schema");
                });

            modelBuilder.Entity("Backend.Sprints.Api.Models.Entities.SprintIssue", b =>
                {
                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<long>("SprintId")
                        .HasColumnType("bigint")
                        .HasColumnName("sprint_id");

                    b.HasKey("IssueId", "SprintId");

                    b.HasIndex("IssueId");

                    b.HasIndex("SprintId");

                    b.ToTable("sprint_issues", "sprints_service_schema");
                });

            modelBuilder.Entity("Backend.Sprints.Api.Models.Entities.SprintIssue", b =>
                {
                    b.HasOne("Backend.Sprints.Api.Models.Entities.Sprint", "Sprint")
                        .WithMany("SprintIssues")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Backend.Sprints.Api.Models.Entities.Sprint", b =>
                {
                    b.Navigation("SprintIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
