FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy

WORKDIR /src

COPY . .

RUN dotnet restore ./dashboard-service/Backend.Dashboards.Api/Backend.Dashboards.Api.csproj

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8085

# Переходим в папку с проектом для запуска
WORKDIR /src/dashboard-service/Backend.Dashboards.Api

CMD ["dotnet", "run"]