FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /src

COPY . .

RUN apk add --no-cache curl

WORKDIR /src/dashboard-service/Backend.Dashboards.Api

CMD ["sh", "-c", "dotnet restore --no-cache=false && dotnet run --urls http://*:8085"]