FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /src

COPY . .

RUN apk add --no-cache curl

WORKDIR /src/sprints-service/Backend.Sprints.Api

CMD ["sh", "-c", "\
    sleep 5 && \
    dotnet restore --force && \
    dotnet run --urls http://*:8084"]