FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine

WORKDIR /src

COPY . .

RUN apk update && apk add --no-cache curl ca-certificates

WORKDIR /src/sprints-service

RUN dotnet restore Backend.Sprints.sln --verbosity detailed --force

WORKDIR /src/sprints-service/Backend.Sprints.Api

CMD ["sh", "-c", "\
    sleep 5 && \
    dotnet restore --force && \
    dotnet run --urls http://*:8084"]