# Eureka server
FROM eclipse-temurin:25-jdk-alpine
WORKDIR /app
RUN apk add --no-cache curl

COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline -B --no-transfer-progress

COPY src ./src

EXPOSE 8761

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]