# Eureka server
FROM eclipse-temurin:25-jdk-jammy
WORKDIR /app
RUN apt-get update && \
    apt-get install -y curl wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY mvnw pom.xml ./
COPY .mvn ./.mvn
RUN chmod +x mvnw

RUN sed -i 's/\r$//' mvnw && chmod +x mvnw

RUN ./mvnw dependency:go-offline -B

COPY src ./src

EXPOSE 8761

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]